lines3=[]
lines3.append('          [name=\'Main model\']' )
lines3.append('\n')
lines3.append('model;') 
lines3.append('\n')
lines3.append('# av_1=c*theta*h^(1+psi);') 
lines3.append('\n')
lines3.append('(1-alpha)*y=av_1;') 
lines3.append('\n')
lines3.append('k = beta*(((exp(b)*c)/(exp(b(+1))*c(+1)))*(exp(b(+1))*alpha*y(+1)+(1-delta)*k));') 
lines3.append('\n')
lines3.append('y=exp(a)*(k(-1)^alpha)*(h^(1-alpha));') 
lines3.append('\n')
lines3.append('k = exp(b)*(y-c)+(1-delta)*k(-1);') 
lines3.append('\n')
lines3.append('a = rho*a(-1)+tau*b(-1) + e;') 
lines3.append('\n')
lines3.append('b = tau*a(-1)+rho*b(-1) + u;') 
lines3.append('\n')
lines3.append('end;')
lines3.append('\n')
with open('t_model2.m', 'w') as f:
    f.writelines(lines3)