function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    kso=(params(16)/(1/params(2)-1+params(3)))^(1/(1-params(16)));
    x0ss=1;
    Xss=1+kso^((1-params(1))*(params(16)-params(17)))*(params(8)/params(7))^params(1)*(exp(params(25))^(1-params(16))/exp(params(26))^(1-params(17))*(params(16)/params(17))^params(17)*((1-params(16))/(1-params(17)))^(1-params(17)))^(1-params(1))+kso^((1-params(1))*(params(16)-params(18)))*(params(9)/params(7))^params(1)*(exp(params(25))^(1-params(16))/exp(params(27))^(1-params(18))*(params(16)/params(18))^params(18)*((1-params(16))/(1-params(18)))^(1-params(18)))^(1-params(1));
    Zss=params(16)+(exp(params(25))^(1-params(16))/exp(params(26))^(1-params(17))*(params(16)/params(17))^params(17)*((1-params(16))/(1-params(17)))^(1-params(17)))^(1-params(1))*(params(8)/params(7))^params(1)*params(17)*kso^((1-params(1))*(params(16)-params(17)))+(exp(params(25))^(1-params(16))/exp(params(27))^(1-params(18))*(params(16)/params(18))^params(18)*((1-params(16))/(1-params(18)))^(1-params(18)))^(1-params(1))*(params(9)/params(7))^params(1)*params(18)*kso^((1-params(1))*(params(16)-params(18)));
    Qss=(Zss-params(16)*Xss)/Xss;
    coy=(1-params(2)*(1-params(3))-params(16)*params(2)*((1+params(5))*(1+params(4))-(1-params(3))))/(1/Xss*(1-params(2)*(1-params(3))*(1+Xss-x0ss))+Qss*params(2)*((1+params(5))*(1+params(4))-(1-params(3))));
    s0on0=params(16)/(1-params(16))*(1-params(16)-Qss*coy)/(params(16)+Qss*coy);
    ys_(3)=(params(16)/(1/params(2)-1+params(3)))^(1/(1-params(16)))*s0on0^(-1);
    ys_(2)=(1+params(4))*(1+params(5))*ys_(3)-(1-params(3))*ys_(3);
    ys_(5)=(1-params(16))*(1-coy*(1-x0ss/Xss))/(1-params(16)-Qss*coy);
    ys_(4)=(1-params(16))*(s0on0*ys_(3))^params(16)/(1-params(16)-Qss*coy);
    ys_(1)=coy*ys_(4);
    ys_(6)=s0on0*ys_(5);
    ys_(3)=log(ys_(3));
    ys_(2)=ys_(2);
    ys_(5)=log(ys_(5));
    ys_(4)=log(ys_(4));
    ys_(1)=log(ys_(1));
    ys_(6)=log(ys_(6));
    ys_(7)=params(16);
    ys_(8)=params(17);
    ys_(9)=params(18);
    ys_(10)=params(25);
    ys_(11)=params(26);
    ys_(12)=params(27);
    % Auxiliary equations
end
