shocks; 
var theta0shock = theta_var0;
var theta1shock = theta_var1;
var theta2shock = theta_var2;
var theta3shock = theta_var3;
var theta4shock = theta_var4;
var theta5shock = theta_var5;
var theta6shock = theta_var6;
var theta7shock = theta_var7;
var theta8shock = theta_var8;
var a0shock = a_var0;
var a1shock = a_var1;
var a2shock = a_var2;
var a3shock = a_var3;
var a4shock = a_var4;
var a5shock = a_var5;
var a6shock = a_var6;
var a7shock = a_var7;
var a8shock = a_var8;
end;